### ISSUE TITLE
Optimization: Refactor of Docker installation 

### ISSUE THREAD

**Issue by ethan0905** [ethan0905/ft_transcendence#24]
The first goal was to dockerized the full Web Application, connect all the services (frontend, backend, database, orm).
The new goal is now to refactor the code, to make it more efficient.

**Comment by ethan0905** [comment]
1- Replaced all files copy by volumes on the repository directly. ✅

**Comment by ethan0905** [comment]
````bash
backend_nestjs    | (node:309) [DEP0164] DeprecationWarning: Implicit coercion to integer for exit code is deprecated.
backend_nestjs    | (Use `node --trace-deprecation ...` to show where the warning was created)
````

**Comment by ethan0905** [comment]
after switching the database inside the repository:
````bash
backend_nestjs    | Starting inspector on 127.0.0.1:9229 failed: address already in use
backend_nestjs    | (node:32) [DEP0164] DeprecationWarning: Implicit coercion to integer for exit code is deprecated.
backend_nestjs    |     at process.exit (node:internal/process/per_thread:201:7)
backend_nestjs    |     at process.<anonymous> (/app/node_modules/@prisma/engine-core/src/library/ExitHooks.ts:63:17)
backend_nestjs    |     at Object.onceWrapper (node:events:627:26)
backend_nestjs    |     at process.emit (node:events:512:28)
backend_nestjs    |     at process.emit (/app/node_modules/source-map-support/source-map-support.js:516:21)
````

**Comment by ethan0905** [comment]
same error
````bash
backend_nestjs    | Starting inspector on 127.0.0.1:9229 failed: address already in use
backend_nestjs    | (node:958) [DEP0164] DeprecationWarning: Implicit coercion to integer for exit code is deprecated.
backend_nestjs    |     at process.exit (node:internal/process/per_thread:201:7)
backend_nestjs    |     at process.<anonymous> (/app/node_modules/@prisma/engine-core/src/library/ExitHooks.ts:63:17)
backend_nestjs    |     at Object.onceWrapper (node:events:627:26)
backend_nestjs    |     at process.emit (node:events:512:28)
backend_nestjs    |     at process.emit (/app/node_modules/source-map-support/source-map-support.js:516:21)
````

**Comment by ethan0905** [comment]
We changed in the backend dockerfile the CMD:
`npm run start ; npx prisma db push` in order to apply the current prisma.schema config on docker build. 
To view the Database after build, you must go inside the container, and run `npx prisma studio`
