### ISSUE TITLE
2FA : When multiple account in db...

### ISSUE THREAD

**Issue by ethan0905** [ethan0905/ft_transcendence#29]
when 2 user in database and 2fa enable for the current test user, 2fa not called on log. Need to dig to understand why

**Comment by ethan0905** [comment]
Additionnal information: This is working again if you reset and reactivate with a new qrcode.

**Comment by ethan0905** [comment]
Fixed the last error in the frontend side.

**Comment by ethan0905** [comment]
> When 2 user in database and 2fa enable for the current test user, 2fa not called on log. Need to dig to understand why.
> 
> Not essential for now, the all process works well.

Two FA is called, but request failed, due to wrong user email

````bash
backend_nestjs    | user to verify:   esafar@student.42.fr
backend_nestjs    | authenticator code to verify:   693309
backend_nestjs    | [Nest] 373  - 04/14/2023, 6:06:19 PM   ERROR [ExceptionsHandler] The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received null
backend_nestjs    | TypeError: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received null
backend_nestjs    |     at new NodeError (node:internal/errors:399:5)
backend_nestjs    |     at Function.from (node:buffer:330:9)
backend_nestjs    |     at new Buffer (node:buffer:285:17)
backend_nestjs    |     at Object.exports.decode (/app/node_modules/thirty-two/lib/thirty-two/thirty-two.js:87:16)
backend_nestjs    |     at Object.keyDecoder (/app/node_modules/@otplib/plugin-thirty-two/index.js:17:20)
backend_nestjs    |     at authenticatorDecoder (/app/node_modules/@otplib/core/index.js:413:18)
backend_nestjs    |     at authenticatorCheckWithWindow (/app/node_modules/@otplib/core/index.js:423:37)
backend_nestjs    |     at Authenticator.checkDelta (/app/node_modules/@otplib/core/index.js:436:12)
backend_nestjs    |     at Authenticator.check (/app/node_modules/@otplib/core/index.js:358:24)
backend_nestjs    |     at Authenticator.verify (/app/node_modules/@otplib/core/index.js:365:17)
````

**Comment by ethan0905** [comment]
+ Vulnerability : When user connects with his 42 account, 2fa is asked but you can bypass by changing the url to /myProfile. To fix this, I simply need to add a check in the <PrivateRoute/> component.

**Comment by ethan0905** [comment]
> > When 2 user in database and 2fa enable for the current test user, 2fa not called on log. Need to dig to understand why.
> > Not essential for now, the all process works well.
> 
> Two FA is called, but request failed, due to wrong user email
> 
> ```shell
> backend_nestjs    | user to verify:   esafar@student.42.fr
> backend_nestjs    | authenticator code to verify:   693309
> backend_nestjs    | [Nest] 373  - 04/14/2023, 6:06:19 PM   ERROR [ExceptionsHandler] The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received null
> backend_nestjs    | TypeError: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received null
> backend_nestjs    |     at new NodeError (node:internal/errors:399:5)
> backend_nestjs    |     at Function.from (node:buffer:330:9)
> backend_nestjs    |     at new Buffer (node:buffer:285:17)
> backend_nestjs    |     at Object.exports.decode (/app/node_modules/thirty-two/lib/thirty-two/thirty-two.js:87:16)
> backend_nestjs    |     at Object.keyDecoder (/app/node_modules/@otplib/plugin-thirty-two/index.js:17:20)
> backend_nestjs    |     at authenticatorDecoder (/app/node_modules/@otplib/core/index.js:413:18)
> backend_nestjs    |     at authenticatorCheckWithWindow (/app/node_modules/@otplib/core/index.js:423:37)
> backend_nestjs    |     at Authenticator.checkDelta (/app/node_modules/@otplib/core/index.js:436:12)
> backend_nestjs    |     at Authenticator.check (/app/node_modules/@otplib/core/index.js:358:24)
> backend_nestjs    |     at Authenticator.verify (/app/node_modules/@otplib/core/index.js:365:17)
> ```

Fixed this issue. The error was related to undefined token been send to backend. So by default, the user email was the first user created in the database.

**Comment by ethan0905** [comment]
> * Vulnerability : When user connects with his 42 account, 2fa is asked but you can bypass by changing the url to /myProfile. To fix this, I simply need to add a check in the PrivateRoute component.

Fixed this issue by integrating a checker in the PrivateRoute component. The all process is working well. Instead of storing the authFactorVerified boolean in the database, best practice would be to store a cookie that is valid for 10min. Not essential but could be great so I am letting the issue open.
